version: '3.8'
services:
  backend:
    image: accounts-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    depends_on:
      - service_db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service_db/accounts

  service_db:
    image: postgres:13.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5439:5432"
    volumes:
      - ./etc/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
